server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com
  #hostname: localhost
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心
    fetch-registry: false
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      defaultZone:  http://eureka7002.com:7002/eureka
  server:
    #关闭自我保护机制
    enable-self-preservation: false
    #检测时间改为2000毫秒
    eviction-interval-timer-in-ms: 2000